version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: on-failure:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coursework
    ports:
      - '5432:5432'
